<?php

namespace eQuest\Api\QuestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserQuestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserQuestsRepository extends EntityRepository
{
}
