eQuest\Api\QuestBundle\Entity\Map:
    type: entity
    table: null
    repositoryClass: eQuest\Api\QuestBundle\Entity\MapRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        building:
            type: string
            length: 255
        floor_no:
            type: integer
        img:
            type: string
            length: 255
    lifecycleCallbacks: {  }
