eQuest\Api\QuestBundle\Entity\Quest:
    type: entity
    table: null
    repositoryClass: eQuest\Api\QuestBundle\Entity\QuestRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        name:
            type: string
            length: 255
        description:
            type: text
        ts:
            type: timestamp
        t_xp:
            type: integer
        targets_to_achive:
            type: text
            column: targets_to_achive
    lifecycleCallbacks: {  }
