eQuest\Api\QuestBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: eQuest\Api\QuestBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
        domain:
            type: string
            length: 255
        avatar:
            type: string
            length: 255
        status:
            type: integer
        type:
            type: integer
        t_xp:
            type: integer
        activ_quest_id:
            type: integer
            column: targets_to_achive
    lifecycleCallbacks: {  }
